import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import '../globals.css'
import { redirect } from 'next/navigation'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  redirect('/admin')
  return (
    <html lang='en'>
      <body className={`${inter.className} ${roboto.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
