import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { SessionProvider } from 'next-auth/react'
import Providers from '@/app/Providers'
import Header from '@/components/scaffold/Header'
import Sidebar from '@/components/scaffold/Sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SessionProvider>
            <div
              className='flex w-full min-h-screen relative'
              id='page-wrapper'
            >
              <Sidebar />
              <div className='flex-grow'>
                <Header />
                <main>{children}</main>
              </div>
            </div>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  )
}
